swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "0.0"
  title: Antx REST API
  
host: TBD

basePath: TBD

schemes:
  - http
  - https
  
consumes:
  - application/json

produces:
  - application/json

paths:
  /calculate:
    post:
      description: calculate cashflows
      parameters:
        - name: spec
          in: query
          description: input and output specs. includes collateral, capital structure, etc
          required: true
          type: object
          properties:
            input:
              type: object
              properties:
                collateral: 
                type: array
                items:
                  $ref: '#/definitions/yyy'
              
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/xxxx'
